Repository RedHatInsights/ros-ocp-backend, pull requests merged in 2023-11, with the labels that each got.

#143 Removed tag added for testing and included cron job scheduling
  .github/workflows/test-ros-kruize-rm.yml
Labels: Ready to merge

#140 RHIROS-1341 fix sorting for workload type
  Makefile
  migrations/000003_create_workloads_table.up.sql
Labels: Ready for review

#144 Fixes #RHIROS-1401 - Dropping csv records with missing resource usage…
  internal/logging/logging.go
  internal/types/workload/workload.go
  internal/utils/aggregator.go
  internal/utils/aggregator_test.go
  internal/utils/metrics.go
Labels: Ready for review

#145 Update Kruize image with latest commit
  kruize-clowdapp.yaml
  scripts/docker-compose.yml
Labels: Ready to merge, 0.0.19_4_rm

#146 RHIROS-1407 Add CodeQL (SAST) GitHub workflow
  .github/workflows/build.yml
  .github/workflows/codeql.yml
  .github/workflows/test-ros-kruize-rm.yml
Labels: Ready for review

#160 RHINENG-5040 namespace type assertion
  internal/services/report_processor.go
  internal/types/kruizePayload/common.go
  internal/types/kruizePayload/updateResult.go
  internal/utils/kruize/kruize_api.go
Labels: Ready for review
