Repository RedHatInsights/ros-ocp-backend, pull requests merged in 2023-06, with the labels that each got.

#86 Fixes #RHIROS-1174 - Added param in clowdapp.yml to disable RBAC
  .DS_Store
  .gitignore
  clowdapp.yaml
  internal/config/config.go
Labels: Ready for review

#84 Fixes #RHIROS-1150 - Adding prometheus metrics to rosocp
  cmd/start.go
  go.mod
  internal/api/server.go
  internal/config/config.go
  internal/model/cluster.go
  internal/model/metrics.go
  internal/model/recommendation_set.go
  internal/model/rh_account.go
  internal/model/workload.go
  internal/model/workload_metrics.go
  internal/services/metrics.go
  internal/services/recommender.go
  internal/services/report_processor.go
  internal/utils/kruize/kruize_api.go
  internal/utils/kruize/metrics.go
  internal/utils/utils.go
Labels: Ready for review

#81 Fixes #RHIROS-1126 - Handle daily data from operator
  clowdapp.yaml
  internal/config/config.go
  internal/model/workload_metrics.go
  internal/services/report_processor.go
Labels: Ready for review

#90 Fixes #RHIROS-1151 - Change http status code from 401 to 403
  internal/api/middleware/rbac.go
Labels: Ready for review

#87 RHIROS-1134 Memory unit conversions
  cmd/db.go
  internal/api/handlers.go
  internal/api/utils.go
  internal/types/kruizePayload/common.go
Labels: Ready to merge

#94 Refs #RHIROS-1194 - Permission should be matched against cluster_uuid
  internal/model/recommendation_set.go
Labels: Ready for review, Urgent

#92 Fixes #RHIROS-1192 - Upgrading kruize image to 0.0.15_rm
  internal/services/recommender.go
  internal/types/kruizePayload/common.go
  scripts/docker-compose.yml
Labels: Ready for review
