Repository RedHatInsights/ros-ocp-backend, pull requests merged in 2023-10, with the labels that each got.

#127 Fixes #RHIROS-1347 - Dynamically create table partitions to optimize …
  internal/model/historical_recommendation_set.go
  internal/model/metrics.go
  internal/model/workload.go
  internal/model/workload_metrics.go
  internal/services/report_processor.go
  migrations/000003_create_workloads_table.up.sql
  migrations/000004_create_recommendation_sets_table.up.sql
  migrations/000005_add_unique_to_recommendation_set.down.sql
  migrations/000005_add_unique_to_recommendation_set.up.sql
  migrations/000005_partition_functions.down.sql
  migrations/000005_partition_functions.up.sql
  migrations/000006_create_workload_metrics_table.down.sql
  migrations/000006_create_workload_metrics_table.up.sql
  migrations/000007_create_historical_recommendation_sets.down.sql
  migrations/000007_create_historical_recommendation_sets.up.sql
  migrations/000008_keep_last_reported.down.sql
  migrations/000008_keep_last_reported.up.sql
  migrations/000009_modify_recommendation_sets_table.down.sql
  migrations/000009_modify_recommendation_sets_table.up.sql
Labels: Do not merge, Ready to merge

#133 [ROS-OCP] Make API specifications available under Insights API documentation
  openapi.json
Labels: Ready for review

#142 Fixes #RHIROS-1402 - Fixed payload creation for kruize updateResult API
  internal/services/report_processor.go
  internal/utils/kruize/kruize_api.go
  internal/utils/utils.go
Labels: Ready for review, Urgent
