Repository RedHatInsights/ros-ocp-backend, pull requests merged in 2023-04, with the labels that each got.

#41 Fix DB constraint
  cmd/db.go
  docs/database/db-schema
  internal/api/utils.go
  internal/model/recommendation_set.go
  migrations/000004_create_recommendation_sets_table.up.sql
  migrations/000005_add_unique_to_recommendation_set.up.sql
Labels: Do not merge, Ready for review

#43 Fixes #RHIROS-1054 - Storing container usage metrics in ROS
  docs/database/db-schema
  docs/database/db-schema.png
  internal/model/workload_metrics.go
  internal/processor/kruize_api.go
  internal/processor/report_processor.go
  internal/services/recommender.go
  internal/types/kruizePayload/updateResult.go
  migrations/000006_create_workload_metrics_table.down.sql
  migrations/000006_create_workload_metrics_table.up.sql
Labels: Ready for review

#47 RHIROS-1068 Store all recommendation sets
  internal/model/recommendation_set.go
  internal/services/recommender.go
  migrations/000005_add_unique_to_recommendation_set.up.sql
Labels: Ready for review

#49 RHIROS-1077 Multiple values per query param
  internal/api/utils.go
  internal/model/recommendation_set.go
Labels: Ready for review

#50 Fixes #RHIROS-1078 - Added new column for source_id
  Makefile
  docs/database/db-schema
  docs/database/db-schema.png
  internal/api/handlers.go
  internal/model/cluster.go
  internal/model/recommendation_set.go
  internal/processor/report_processor.go
  internal/processor/utils.go
  migrations/000002_create_clusters_table.up.sql
Labels: Ready for review

#55 Fix Makefile target archive-to-minio
  Makefile
Labels: Ready for review

#52 Refactor codebase
  cmd/aggregator.go
  cmd/start.go
  internal/services/recommender.go
  internal/services/report_processor.go
  internal/types/kafkaMsg.go
  internal/utils/aggregator.go
  internal/utils/kruize/kruize_api.go
  internal/utils/utils.go
  internal/utils/utils_test.go
Labels: Ready for review

#53 RHIROS-1081 Misc openapi updates
  internal/api/docs/v1/openapi.json
  scripts/ros_ocp_backend.postman_collection.json
Labels: Ready for review, Ready to merge

#24 Fixes #RHIROS-1024 - Added RBAC and identity middleware
  Makefile
  clowdapp.yaml
  go.mod
  go.sum
  internal/api/docs/v1/openapi.json
  internal/api/handlers.go
  internal/api/middleware/identity.go
  internal/api/middleware/rbac.go
  internal/api/server.go
  internal/api/utils.go
  internal/config/config.go
  internal/types/identity/identity.go
  internal/types/rbacResponse.go
  internal/types/resourceObject.go
Labels: Ready for review

#61 Fixes: #RHIROS-1067 - Upgrade kruize image to 0.0.13_rm
  clowdapp.yaml
  internal/api/handlers.go
  internal/services/recommender.go
  internal/services/report_processor.go
  internal/types/experimentEvent.go
  internal/types/kruizePayload/common.go
  internal/types/kruizePayload/updateResult.go
  scripts/cdappconfig.json
  scripts/docker-compose.yml
Labels: Ready for review
