Repository RedHatInsights/ros-ocp-backend, pull requests merged in 2023-07, with the labels that each got.

#96 RHIROS-1134 Remove implicit rounding
  internal/api/utils.go
Labels: Ready for review, Ready to merge

#93 Adding nginx to dev setup to submit csv to ROS-OCP
  Makefile
  scripts/docker-compose.yml
  scripts/samples/ros-ocp-usage.csv
Labels: Ready for review

#98 Fixes #RHIROS-1211 - forward current value in recommendation
  internal/api/utils.go
  internal/types/kruizePayload/common.go
  openapi.json
Labels: Ready for review

#97 Fixes #RHIROS-1219 - upgrade Kruize to 0.0.16_rm
  clowdapp.yaml
  scripts/docker-compose.yml
Labels: Ready for review

#91 Fixes #RHIROS-1193 - Adding hash key while producing the kafka message
  internal/kafka/producer.go
  internal/services/recommender.go
  internal/services/report_processor.go
Labels: Ready for review

#95 RHIROS-1198 CPU: cores to millicores
  cmd/db.go
  internal/api/handlers.go
  internal/api/utils.go
  openapi.json
Labels: Ready to merge

#102 RHIROS-1220 Kruize as ClowdApp kind
  clowdapp.yaml
  kruize-clowdapp.yaml
Labels: Ready for review

#104 Fixes #RHIROS-1267 - Create separate table store historical recommend…
  internal/model/historical_recommendation_set.go
  internal/model/recommendation_set.go
  internal/services/recommender.go
  migrations/000007_create_historical_recommendation_sets.down.sql
  migrations/000007_create_historical_recommendation_sets.up.sql
  migrations/000008_keep_last_reported.down.sql
  migrations/000008_keep_last_reported.up.sql
  migrations/000009_modify_recommendation_sets_table.down.sql
  migrations/000009_modify_recommendation_sets_table.up.sql
Labels: Ready for review
