Repository RedHatInsights/ros-ocp-backend, pull requests merged in 2024-01, with the labels that each got.

#177 Allow mounting volumes when selinux is enforcing mode
  scripts/docker-compose.yml
Labels: Ready for review

#176 Don't silent curl commands
  Makefile
Labels: Ready for review

#179 RHINENG-6226 Recommendation Poller service
  Makefile
  clowdapp.yaml
  cmd/start.go
  internal/config/config.go
  internal/kafka/consumer.go
  internal/kafka/producer.go
  internal/logging/logging.go
  internal/model/historical_recommendation_set.go
  internal/model/recommendation_set.go
  internal/services/houseKeeper.go
  internal/services/recommendation_poller.go
  internal/services/report_processor.go
  internal/types/kafkaMsg.go
  scripts/docker-compose.yml
  scripts/samples/ros-ocp-usage-24Hrs.csv
Labels: Ready for review

#180 Fixes #RHINENG-2879 - Pin Golang version for go-toolset
  Dockerfile
  go.mod
Labels: Ready for review, Demo worthy

#129 RHIROS-1326 Kruize 0.0.20.1_rm Integration
  .gitignore
  internal/api/utils.go
  internal/services/metrics.go
  internal/services/recommendation_poller.go
  internal/services/report_processor.go
  internal/types/kruizePayload/common.go
  internal/types/kruizePayload/createExperiment.go
  internal/utils/kruize/kruize_api.go
  internal/utils/kruize/metrics.go
  kruize-clowdapp.yaml
  openapi.json
  scripts/docker-compose.yml
  scripts/samples/ros-ocp-usage-24Hrs.csv
Labels: Do not merge, ready for QE, 0.0.20_rm
