Repository RedHatInsights/ros-ocp-backend, pull requests merged in 2024-11, with the labels that each got.

#269 Refs - #RHINENG-13369 Setting kruize local env variable to false
  kruize-clowdapp.yaml
Labels: Ready to merge

#108 remove machine_pool from clowdapp files
  clowdapp.yaml
  kruize-clowdapp.yaml
Labels: Do not merge

#267 Update go version to 1.22
  .github/workflows/build.yml
  Dockerfile
  go.mod
  go.sum
Labels: Waiting on contributor
