Repository RedHatInsights/ros-ocp-backend, pull requests merged in 2024-06, with the labels that each got.

#219 RHINENG-10255 Unit conversion on ROS OCP backend
  internal/api/common.go
  internal/api/handlers.go
  internal/api/utils.go
  internal/types/kruizePayload/common.go
  kruize-clowdapp.yaml
  openapi.json
  scripts/docker-compose.yml
Labels: Do not merge, Ready for review

#217 RHINENG-9376 Assert workload before relating recommendation record
  internal/model/workload.go
  internal/services/recommendation_poller.go
Labels: Ready for review, Ready to merge

#221 Fixes #RHINENG-9599 - Added created_at timestamp in rh_accounts table
  migrations/000013_add_timestamp_in_rh_accounts.down.sql
  migrations/000013_add_timestamp_in_rh_accounts.up.sql
Labels: Ready for review
